telefonicasc/etl-framework

python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/tc_etl_lib/cb.py

Reference: https://github.com/telefonicasc/etl-framework/issues/13

Added q, mq, id and geolocation filters to get entities

---

python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/22

Step: 0.2.0-next -> 0.3.0

---

python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/23

Step: 0.3.0 -> 0.3.0-next

---

python-lib/requirements.txt
python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/35

Step: 0.4.0-next -> 0.5.0

---

python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/36

Step: 0.5.0 -> 0.5.0-next 

---

python-lib/requirements.txt
python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/40

Step: 0.5.0-next -> 0.6.0

---

python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/41

Step: 0.6.0 -> 0.6.0-next

---

python-lib/requirements.txt
python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/44

Step: 0.6.0-next -> 0.7.0

---

python-lib/tc_etl_lib/setup.py

Step: 0.7.0 -> 0.7.0-next

---

.github/workflows/unit-testing.yml
python-lib/requirements.txt
python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/tc_etl_lib/test_store.py

Relacionado con la PR #46, esta PR añade documentation in GitActions para testing.

ADD testing documentation

---

python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Step: 0.7.0-next -> 0.8.0

---

python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/49

Step: 0.8.0 -> 0.8.0-next

---

python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/59

Step: 0.8.0.post -> 0.9.0

---

python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/60

Step: 0.9.0 -> 0.9.0.post

---

etls/hello-world/requirements.txt
python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/63

Step: 0.9.0.post -> 0.10.0

---

python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/64

Step: 0.10.0 -> 0.10.0.post

---

python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/tc_etl_lib/cb.py

feat: del and init handle warning

---

etls/hello-world/requirements.txt
python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Step: 0.10.0.post -> 0.11.0

---

python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/75

Step: 0.11.0 -> 0.11.0.post

---

etls/hello-world/requirements.txt
python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/80

Step: 0.11.0.post -> 0.12.0

---

python-lib/tc_etl_lib/setup.py

Step: 0.12.0 -> 0.12.0.post

---

python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Soluciona problemas de incompatibilidad con numpy (issue #89)

fix-numpy-dependency

---

python-lib/tc_etl_lib/README.md

FIX Changelog issue reference

---

etls/hello-world/requirements.txt
python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Step: 0.12.0.post -> 0.13.0

---

python-lib/tc_etl_lib/setup.py

step 0.13.0 -> 0.13.0.post

---

etls/hello-world/requirements.txt
python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/91

Step: 0.13.0.post -> 0.14.0

---

python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/92

Step: 0.14.0 -> 0.14.0.post

---

python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

He adaptado el código para permitir versiones superiores en las librerías requests, urllib3, pandas y numpy.

Cambios para permitir versiones superiores en librerías.

---

etls/hello-world/requirements.txt
python-lib/tc_etl_lib/README.md
python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/97

Step: 0.14.0.post -> 0.15.0

---

python-lib/tc_etl_lib/setup.py

Step: 0.15.0 -> 0.15.0.post

---

python-lib/tc_etl_lib/setup.py

Mimics PR https://github.com/telefonicasc/etl-framework/pull/103

Step: 0.16.0 -> 0.16.0.post
